services:
  postgres:
    image: postgres:bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Redberry2024
      POSTGRES_DB: redberry
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_STRING: postgres://postgres:Redberry2024@postgres:5432/redberry?sslmode=disable
    depends_on:
      - postgres
